# Generated by Django 5.0.3 on 2025-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_reply_to_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
